services:
  skynetjs:
    build:
      context: .
      target: production
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9229:9229"
    env_file:
      - .env